const CHANGE_COUNTER = 'CHANGE_COUNTER';
const CHANGE_TASK_TEXT = 'CHANGE_TASK_TEXT';
const ADD_TASK = 'ADD_TASK';
const COMPLETE_TASK = 'COMPLETE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const CHANGE_PROJECT_TEXT = 'CHANGE_PROJECT_TEXT';
const FIND_PROJECT = 'FIND_PROJECT';

export default {
  CHANGE_COUNTER,
  CHANGE_TASK_TEXT,
  ADD_TASK,
  COMPLETE_TASK,
  DELETE_TASK,
  CHANGE_PROJECT_TEXT,
  FIND_PROJECT,
};
