const CHANGE_COUNTER = 'CHANGE_COUNTER';
const CHANGE_TASK_TEXT = 'CHANGE_TASK_TEXT';
const ADD_TASK = 'ADD_TASK';
const COMPLETE_TASK = 'COMPLETE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const ADD_DATE = 'ADD_DATE';

export default {
  CHANGE_COUNTER,
  CHANGE_TASK_TEXT,
  ADD_TASK,
  COMPLETE_TASK,
  DELETE_TASK,
  ADD_DATE,
};
