export const CHANGE_PROJECT_TEXT = 'CHANGE_PROJECT_TEXT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const FIND_PROJECTS = 'FIND_PROJECTS';
