export const CHANGE_PROJECT_TEXT = 'CHANGE_PROJECT_TEXT';
export const FIND_PROJECT_REQUEST = 'FIND_PROJECT_REQUEST';
export const FIND_PROJECT_OK = 'FIND_PROJECT_OK';
export const FIND_PROJECT_FAIL = 'FIND_PROJECT_FAIL';
export const FIND_PROJECT_FETCH = 'FIND_PROJECT_FETCH';
